/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "MW.begin.pb-c.h"
void   mw__begin__init
                     (Mw__Begin         *message)
{
  static Mw__Begin init_value = MW__BEGIN__INIT;
  *message = init_value;
}
size_t mw__begin__get_packed_size
                     (const Mw__Begin *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mw__begin__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mw__begin__pack
                     (const Mw__Begin *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mw__begin__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mw__begin__pack_to_buffer
                     (const Mw__Begin *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mw__begin__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mw__Begin *
       mw__begin__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mw__Begin *)
     protobuf_c_message_unpack (&mw__begin__descriptor,
                                allocator, len, data);
}
void   mw__begin__free_unpacked
                     (Mw__Begin *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mw__begin__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mw__begin__field_descriptors[3] =
{
  {
    "s_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mw__Begin, s_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mw__Begin, d_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mw__Begin, state),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mw__begin__field_indices_by_name[] = {
  1,   /* field[1] = d_id */
  0,   /* field[0] = s_id */
  2,   /* field[2] = state */
};
static const ProtobufCIntRange mw__begin__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mw__begin__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "mw.begin",
  "Begin",
  "Mw__Begin",
  "mw",
  sizeof(Mw__Begin),
  3,
  mw__begin__field_descriptors,
  mw__begin__field_indices_by_name,
  1,  mw__begin__number_ranges,
  (ProtobufCMessageInit) mw__begin__init,
  NULL,NULL,NULL    /* reserved[123] */
};
