/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "MW.nextss_start.pb-c.h"
void   mw__nextss_start__init
                     (Mw__NextssStart         *message)
{
  static Mw__NextssStart init_value = MW__NEXTSS_START__INIT;
  *message = init_value;
}
size_t mw__nextss_start__get_packed_size
                     (const Mw__NextssStart *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mw__nextss_start__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mw__nextss_start__pack
                     (const Mw__NextssStart *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mw__nextss_start__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mw__nextss_start__pack_to_buffer
                     (const Mw__NextssStart *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mw__nextss_start__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mw__NextssStart *
       mw__nextss_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mw__NextssStart *)
     protobuf_c_message_unpack (&mw__nextss_start__descriptor,
                                allocator, len, data);
}
void   mw__nextss_start__free_unpacked
                     (Mw__NextssStart *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mw__nextss_start__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mw__nextss_start__field_descriptors[5] =
{
  {
    "s_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mw__NextssStart, s_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mw__NextssStart, d_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "superstep",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mw__NextssStart, superstep),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node_msg",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mw__NextssStart, node_msg),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aggr_global",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Mw__NextssStart, n_aggr_global),
    PROTOBUF_C_OFFSETOF(Mw__NextssStart, aggr_global),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mw__nextss_start__field_indices_by_name[] = {
  4,   /* field[4] = aggr_global */
  1,   /* field[1] = d_id */
  3,   /* field[3] = node_msg */
  0,   /* field[0] = s_id */
  2,   /* field[2] = superstep */
};
static const ProtobufCIntRange mw__nextss_start__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor mw__nextss_start__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "mw.nextss_start",
  "NextssStart",
  "Mw__NextssStart",
  "mw",
  sizeof(Mw__NextssStart),
  5,
  mw__nextss_start__field_descriptors,
  mw__nextss_start__field_indices_by_name,
  1,  mw__nextss_start__number_ranges,
  (ProtobufCMessageInit) mw__nextss_start__init,
  NULL,NULL,NULL    /* reserved[123] */
};
