/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "WM.curss_finish.pb-c.h"
void   wm__curss_finish__init
                     (Wm__CurssFinish         *message)
{
  static Wm__CurssFinish init_value = WM__CURSS_FINISH__INIT;
  *message = init_value;
}
size_t wm__curss_finish__get_packed_size
                     (const Wm__CurssFinish *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wm__curss_finish__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wm__curss_finish__pack
                     (const Wm__CurssFinish *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wm__curss_finish__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wm__curss_finish__pack_to_buffer
                     (const Wm__CurssFinish *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wm__curss_finish__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wm__CurssFinish *
       wm__curss_finish__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wm__CurssFinish *)
     protobuf_c_message_unpack (&wm__curss_finish__descriptor,
                                allocator, len, data);
}
void   wm__curss_finish__free_unpacked
                     (Wm__CurssFinish *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wm__curss_finish__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor wm__curss_finish__field_descriptors[9] =
{
  {
    "s_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wm__CurssFinish, s_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wm__CurssFinish, d_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "superstep",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wm__CurssFinish, superstep),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "compute",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wm__CurssFinish, compute),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recv_msg",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wm__CurssFinish, recv_msg),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sent_msg",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wm__CurssFinish, sent_msg),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "worker_msg",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    PROTOBUF_C_OFFSETOF(Wm__CurssFinish, n_worker_msg),
    PROTOBUF_C_OFFSETOF(Wm__CurssFinish, worker_msg),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "act_vertex",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wm__CurssFinish, act_vertex),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aggr_local",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Wm__CurssFinish, n_aggr_local),
    PROTOBUF_C_OFFSETOF(Wm__CurssFinish, aggr_local),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wm__curss_finish__field_indices_by_name[] = {
  7,   /* field[7] = act_vertex */
  8,   /* field[8] = aggr_local */
  3,   /* field[3] = compute */
  1,   /* field[1] = d_id */
  4,   /* field[4] = recv_msg */
  0,   /* field[0] = s_id */
  5,   /* field[5] = sent_msg */
  2,   /* field[2] = superstep */
  6,   /* field[6] = worker_msg */
};
static const ProtobufCIntRange wm__curss_finish__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor wm__curss_finish__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "wm.curss_finish",
  "CurssFinish",
  "Wm__CurssFinish",
  "wm",
  sizeof(Wm__CurssFinish),
  9,
  wm__curss_finish__field_descriptors,
  wm__curss_finish__field_indices_by_name,
  1,  wm__curss_finish__number_ranges,
  (ProtobufCMessageInit) wm__curss_finish__init,
  NULL,NULL,NULL    /* reserved[123] */
};
