/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_WM_2eend_2eproto__INCLUDED
#define PROTOBUF_C_WM_2eend_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Wm__End Wm__End;


/* --- enums --- */


/* --- messages --- */

struct  _Wm__End
{
  ProtobufCMessage base;
  int32_t s_id;
  int32_t d_id;
  int32_t state;
};
#define WM__END__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&wm__end__descriptor) \
    , 0, 0, 0 }


/* Wm__End methods */
void   wm__end__init
                     (Wm__End         *message);
size_t wm__end__get_packed_size
                     (const Wm__End   *message);
size_t wm__end__pack
                     (const Wm__End   *message,
                      uint8_t             *out);
size_t wm__end__pack_to_buffer
                     (const Wm__End   *message,
                      ProtobufCBuffer     *buffer);
Wm__End *
       wm__end__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   wm__end__free_unpacked
                     (Wm__End *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Wm__End_Closure)
                 (const Wm__End *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor wm__end__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_WM_2eend_2eproto__INCLUDED */
