/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "WW.nodemsg_list.pb-c.h"
void   ww__nodemsg_list__init
                     (Ww__NodemsgList         *message)
{
  static Ww__NodemsgList init_value = WW__NODEMSG_LIST__INIT;
  *message = init_value;
}
size_t ww__nodemsg_list__get_packed_size
                     (const Ww__NodemsgList *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ww__nodemsg_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ww__nodemsg_list__pack
                     (const Ww__NodemsgList *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ww__nodemsg_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ww__nodemsg_list__pack_to_buffer
                     (const Ww__NodemsgList *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ww__nodemsg_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ww__NodemsgList *
       ww__nodemsg_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ww__NodemsgList *)
     protobuf_c_message_unpack (&ww__nodemsg_list__descriptor,
                                allocator, len, data);
}
void   ww__nodemsg_list__free_unpacked
                     (Ww__NodemsgList *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ww__nodemsg_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ww__nodemsg_list__field_descriptors[6] =
{
  {
    "s_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ww__NodemsgList, s_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ww__NodemsgList, d_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "superstep",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ww__NodemsgList, superstep),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_msgs",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ww__NodemsgList, num_msgs),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg_size",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ww__NodemsgList, msg_size),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgs",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Ww__NodemsgList, msgs),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ww__nodemsg_list__field_indices_by_name[] = {
  1,   /* field[1] = d_id */
  4,   /* field[4] = msg_size */
  5,   /* field[5] = msgs */
  3,   /* field[3] = num_msgs */
  0,   /* field[0] = s_id */
  2,   /* field[2] = superstep */
};
static const ProtobufCIntRange ww__nodemsg_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor ww__nodemsg_list__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ww.nodemsg_list",
  "NodemsgList",
  "Ww__NodemsgList",
  "ww",
  sizeof(Ww__NodemsgList),
  6,
  ww__nodemsg_list__field_descriptors,
  ww__nodemsg_list__field_indices_by_name,
  1,  ww__nodemsg_list__number_ranges,
  (ProtobufCMessageInit) ww__nodemsg_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
